/*
 * This source file was generated by the Gradle 'init' task
 */
package ca.group12;

public class App {
    public String getGreeting() {
        return "Hello Reindeers!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
